// Copyright 2022 Elanskiy Alexandr
#ifndef MODULES_ELANSKI_ALEXANDR_EULER_FUNCTION_INCLUDE_EULER_FUNCTION_H_
#define MODULES_ELANSKI_ALEXANDR_EULER_FUNCTION_INCLUDE_EULER_FUNCTION_H_

class EulerFunction {
 public:
  static int Calculate(int number);
};

#endif  // MODULES_ELANSKI_ALEXANDR_EULER_FUNCTION_INCLUDE_EULER_FUNCTION_H_
